## operation 
0. Matrix Multiplication (np.matmul())

- 행렬의 곱셈

In [ ]:
import numpy as np

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)

[[19 22]
 [43 50]]


### 1. Matrix Multiplication (np.dot())
- NumPy provides the dot function to perform matrix multiplication

- 여기서 말하는 'dot'은 dot product이기도 하지만, 2d array가 주어지면, 행렬의 곱 연산을 한다.

- 1D array가 주어지면 우리가 아는 그 dot product를 계산한다.

####  Dot product
dot product는 벡터 성분들의 곱의 합을 계산한다. 예를 들어 v = [v1, v2, v3], w = [w1, w2, w3] 일 때,

dot product는 v1`*`w1 + v2`*`w2 + v3`*`w3 이다.

두 2*2 행렬 v와 w에 대해 dot product를 계산하면, 벡터 v=[[1,2],[3,4]] 와 w=[[5,6],[7,8]] 일 때,

dot product는 각가의 열에 대해 [1`*`5 + 2`*`6, 3`*`7 + 4`*`8] = [17, 53] 이다. 

내적은 “동일 길이의 벡터” 사이에서만 정의된다. 

In [ ]:
# 1d array
print(np.dot(([5, 6, 7]), ([5, 6, 7])))

# 2d array
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])

result = np.dot(a, b)

print(result)


110
[[12  9]
 [32 17]]


In [ ]:
# implement dot_manual(v, w)
# compare with np.dot(v, w)
def dot_manual(v, w):
    result = 0
    for i in range(len(v)):
        result += v[i]* w[i] # 각 성분을 곱한 후 더함
    return result


dotmanual = dot_manual(v[0], w[0]) # 첫 번째 열벡터들에 대해 수동으로 내적 계산
dotnumpy = np.dot(v[0], w[0]) # numpy를 사용한 내적 계산

print(dotmanual)
print(dotnumpy)



95
95
95



### 2. Inner Product (np.inner())

- Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.


In [ ]:
# 1d array
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

inner_product = np.inner(array1, array2)
dot_product = np.dot(array1, array2)
print(inner_product)
print(dot_product)

# multidimensional example
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
c = np.inner(a, b)
d = np.dot(a, b)


print(c) # 각 행간의 내적
print(d) # matmult와 같은 값. 즉 행렬의 곱셈

32
32
[[ 8 10]
 [26 22]]
[[12  9]
 [32 17]]


### 3. Vector Dot Product (np.vdot())
- returns the dot product of two vectors. It differs from dot as it treats the input arrays as vectors and performs their dot product

- 항상 scalar를 반환

- Note that higher-dimensional arrays are flattened. (Frobenius inner product)

In [ ]:
# 여기서 보면 알수 있듯이 2d array을 넣고 vdot을 하면, 그걸 잡아 늘려서 1d array를 만들어 버린다.
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
result = np.vdot(a, b)
result2 = np.dot(a,b)
result3 = np.inner(a,b)

print(result)
print(result2)
print(result3)

30
[[12  9]
 [32 17]]
[[ 8 10]
 [26 22]]


### 중간 비교
dot vs inner vs vdot
| 함수         | 차원             | 결과 형태  | 의미          |
| ---------- | -------------- | ------ | ----------- |
| `np.dot`   | 1D→스칼라, 2D→행렬곱 | 스칼라 혹은 행렬    | 선형대수 표준 연산  |
| `np.inner` | 항상 마지막 축 기준    | 다차원 가능 | 행끼리 내적      |
| `np.vdot`  | 전체 flatten     | 스칼라    | 켤레 포함 전체 내적 |



In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))
print(np.inner(a,b))
print(np.vdot(a,b))

32
32
32


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B))
print(np.inner(A, B))
print(np.vdot(A, B))

[[19 22]
 [43 50]]
[[17 23]
 [39 53]]
70


| 함수              | 결과                  | 해석                      |
| --------------- | ------------------- | ----------------------- |
| `np.dot(A,B)`   | `[[19,22],[43,50]]` | 행렬곱 (행×열)               |
| `np.inner(A,B)` | `[[17,23],[39,53]]` | 각 행과 행 간 내적 (4개)        |
| `np.vdot(A,B)`  | `70`                | 전체 원소 곱합 (Frobenius 내적) |

벡터 내적만 구할 땐 dot, inner, vdot 모두 가능

행렬 곱은 dot만 사용

복소수 데이터에서는 vdot이 정확한 “수학적 내적” (from numpy manual)

행렬 전체 내적(Frobenius) 은 vdot 또는 np.trace(A.T@B)

행별/열별 내적은 inner (행렬차원 유지)

### Extra : Trace (np.trace())

The trace of a square matrix is the sum of its diagonal elements:

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
trace_sum = np.trace(matrix)
print(trace_sum) # 대각 원소끼리 더함 대각 원소: 1+4

a = np.arange(24).reshape((2,2,2,3))

print(np.trace(a)) # 2D가 아니면, 마지막 axis (2,3)에 대하여 주대각선 (첫 대각선)상의 원소 합을 계산
print(np.trace(a).shape) 
print(np.shape(a))

5
[[18 20 22]
 [24 26 28]]
(2, 3)
(2, 2, 2, 3)


위의 예에서 

[[[[ 0  1  2]

   [ 3  4  5]]

여기서 0 + 4

  [[ 6  7  8]

   [ 9 10 11]]]

여기서 6+10

 [[[12 13 14]

   [15 16 17]]


여기서 12 + 16

  [[18 19 20]

   [21 22 23]]]]

여기서 18 + 22

결과적으로 

np.trace(a) =

[[ 4, 16],

 [28, 40]]

 ### 4. Outer Product (np.outer())
 - 벡터의 외적

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

outer_product = np.outer(array1, array2)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### 5. Determinant (det)

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print(determinant)

-2.0000000000000004


### 6. Inverse (np.linalg.inv())
- 역함수 계산

In [ ]:
# To find the inverse of a square matrix, you can use the inv function:
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


### 7. Matrix power calculation (np.linalg.matrix_power())
- For positive integers n, the power is computed by repeated matrix squarings and matrix multiplications. 

- If n == 0, the identity matrix of the same shape as M is returned. If n < 0, the inverse is computed and then raised to the abs(n).

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
power = 3

matrix_to_power = np.linalg.matrix_power(matrix, power)
print(matrix_to_power)

[[ 37  54]
 [ 81 118]]


### Extra 행렬의 원소끼리의 곱


In [ ]:
# 행렬의 원소곱
A = np.array([[1,5], [6,4], [2,7]])
B = np.array([[5,-1], [1,2], [4,1]])
C = np.multiply(A, B)
print(C)



[[ 5 -5]
 [ 6  8]
 [ 8  7]]


### Extra : Tensor Dot Product (np.tensordot())

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

tensor_dot_product = np.tensordot(array1, array2, axes=1)
print(tensor_dot_product)

[[19 22]
 [43 50]]
