# Transpose

In [8]:
import numpy as np
import sympy as sp


a,b,c,d,i,j,k,h = sp.symbols('a b c d i j k h')

# 1. Transpose (.T)
대각선을 기준으로 회전

In [52]:
m = sp.Matrix([
    ["a", "b", "c"],
    ["d", "e", "f"],
    ["g", "h", "i"]
            ])

m.T

Matrix([
[a, d, g],
[b, e, h],
[c, f, i]])

In [60]:
print(np.transpose(m))  # 같은 결과

[[a d g]
 [b e h]
 [c f i]]


# 2. Inverse (np.linalg.inv())

In [3]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [7]:
m = sp.Matrix([
    ["a", "b", "c"],
    ["d", "e", "f"],
    ["g", "h", "i"]
            ])
sp.Inverse(m)

Matrix([
[a, b, c],
[d, e, f],
[g, h, i]])**(-1)

## 3. Zero and Identity matrix



In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.zeros(3)

array([0., 0., 0.])