In [ ]:
import numpy as np
import matplotlib as plt
import sympy as sy
import scipy as sp


create the two-dimensional array 
 extract the subset array

In [3]:
arrayA = np.array([[1,2,3,4,5],
                    [2,3,4,5,6],
                    [3,4,5,6,8],
                    [4,5,6,7,8]])

sliceA = arrayA[2:4, 1:4]
print(arrayA)
print(sliceA)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 8]
 [4 5 6 7 8]]
[[4 5 6]
 [5 6 7]]


for loop to create a one-dimensional array 
with odd numbers from 1 to 9.

In [ ]:
arrayB = np.array([])
for i in range(10):
    if i % 2 != 0 :
        arrayB = np.append(arrayB, i)
print(arrayB)


[1. 3. 5. 7. 9.]


np.float64(3.0)

transpose

In [ ]:
arrayC = np.array([-1,-2, -3, -4, -5])
transpose_array = arrayC.reshape(5,1)
print(transpose_array)

[[-1]
 [-2]
 [-3]
 [-4]
 [-5]]
[-1 -2 -3 -4 -5]
