In [2]:
import numpy as np
import matplotlib as plt
import sympy as sy
import scipy as sp

# Matrix types

1. Diagnol matrix
- 대각 방향의 성분을 제외하고 나머지 성분이 모두 0인 행렬

2. Upper triangular matrix (U)
- 대각 성분을 기준으로 아래는 모두 0인 행렬

3. Lower triangular matrix (L)
- 대각 성분을 기준으로 위가 모두 0인 행렬

4. Permutation matrixs (P)
- row exchange해주는 행렬



In [8]:
# 대각 행렬
D = np.diag([1, 2, 3])
print(D)

# Upper triangular matrix
U = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(U)

# Lower triangular matrix
L = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(L)

# permutation matrix
P = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]) # 이 행렬은 row1이 row3, row2가 row1, row3이 row2로 바뀌는 행렬
print(P)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]


# LU decomposition

LU 분해란,

어떤 행렬 A를 Lower triangular matrix L과 Upper triangular matrix U의 곱으로 표현하는 것이다. 이 방법은 선형 방정식 시스템을 푸는 데 유용하다. 왜냐하면 L과 U를 사용해서 계산의 복잡성을 줄일 수 있기 때문이다.

식으로 표현하면 A = LU

In [ ]:
# 

In [13]:
# LU 분해
A = np.array([[4, 3], [6, 3], [8, 4], [10, 5]])
_, L, U = sp.linalg.lu(A)
print("A:\n", A)
print("L:\n", L)
print("U:\n", U)

A:
 [[ 4  3]
 [ 6  3]
 [ 8  4]
 [10  5]]
P:
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L:
 [[ 1.0000000e+00  0.0000000e+00]
 [ 4.0000000e-01  1.0000000e+00]
 [ 8.0000000e-01  0.0000000e+00]
 [ 6.0000000e-01 -4.4408921e-16]]
U:
 [[10.  5.]
 [ 0.  1.]]


# PLU decomposition

PLU 분해란,

어떤 행렬 A를 permutation matrix P, Lower triangular matrix L, Upper triangular matrix U의 곱으로 표현하는 것이다. LU분해와 비슷하지만, 어떤 행렬은 행을 교환해야하는 경우가 있는데 이 경우를 permutation matrix를 추가하면서 해결한다. 식으로 표현하면, PA = LU

In [14]:
# PLU 분해
A = np.array([[0, 3, 1], [6, 3, 2], [8, 4, 3], [10, 5, 4]])
P, L, U = sp.linalg.lu(A)
print("A:\n", A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

A:
 [[ 0  3  1]
 [ 6  3  2]
 [ 8  4  3]
 [10  5  4]]
P:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
L:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 6.00000000e-01 -1.48029737e-16  1.00000000e+00]
 [ 8.00000000e-01  0.00000000e+00  5.00000000e-01]]
U:
 [[10.   5.   4. ]
 [ 0.   3.   1. ]
 [ 0.   0.  -0.4]]
